---

- name: create sysadmins group
  group:
    name: sysadmins
    state: present
  become: true

- name: create superuser
  user:
    name: admin
    groups:
    - sysadmins
  become: true

- name: create user for cluster utilisation report
  user:
    name: cmjobuser
    groups:
    - hadoop
  become: true