---

- name: send keytabs to gateway
  copy:
    src: tmp/keytabs/
    dest: /opt/keytabs
    owner: centos
    mode: '0644'
  become: true
  tags:
    - upload_keytabs

- name: kinit as hdfs user
  shell: kinit hdfs -kt /opt/keytabs/hdfs.keytab
  tags:
    - create_admin

- name: create admin directory
  shell: hadoop fs -mkdir /user/admin
  tags:
    - create_admin

- name: chown admin directory
  shell: hadoop fs -chown admin /user/admin
  tags:
    - create_admin

- name: fix hive warehouse dir for Sentry
  shell: hdfs dfs -chmod -R 771 /user/hive/warehouse
  tags:
    - Sentry Setup