---

- name: create sysadmin
  hosts: cdh_servers
  roles:
    - common
  tags:
    - create_sysadmin

- name: Configure kb5
  hosts: krb5_server
  roles:
    - krb5
  tags: 
    - kerberos
    
- name: Configure Gateway and users
  hosts: edge_servers
  roles:
    - edge
  tags:
    - edge