---

- name: add yum epel
  yum:
    name: epel-release
    state: present
  become: true
  tags: pip

- name: install pip 
  yum:
    name: python-pip
    state: present
  become: true
  tags: pip

- name: install python lib
  pip:
    name: pexpect
  become: true
  tags: pip

- name: Create keytabs folder
  file:
    path: /opt/keytabs
    state: directory
    owner: centos
    mode: '0755'
  become: true
  tags:
    - superuser

- name: Create HDFS Superuser
  shell: sudo -u cloudera-scm kadmin -w {{ krb5_kdc_admin_passwd }} -q "addprinc -pw {{ krb5_hdfs_master_passwd }} hdfs"
  tags:
    - superuser

- name: Generate HDFS Keytab
  expect:
    command: ktutil 
    responses:
      ktutil: 
        - "add_entry -password -p hdfs@CLOUDERA.COM -k 1 -e aes256-cts"
        - "wkt /opt/keytabs/hdfs.keytab"
        - "quit"
      Password: '{{ krb5_hdfs_master_passwd }}'
  tags:
    - superuser

- name: Create admin user since Hue uses that
  shell: sudo -u cloudera-scm kadmin -w {{ krb5_kdc_admin_passwd }} -q "addprinc -pw {{ krb5_admin_user_passwd }} admin"
  tags:
    - adminuser

- name: Generate Hive Keytab
  expect:
    command: ktutil 
    responses:
      ktutil: 
        - "add_entry -password -p admin@CLOUDERA.COM -k 1 -e aes256-cts"
        - "wkt /opt/keytabs/admin.keytab"
        - "quit"
      Password: '{{ krb5_admin_user_passwd }}'
  tags:
    - adminuser


- name: Create sysadmin user 
  shell: sudo -u cloudera-scm kadmin -w {{ krb5_kdc_admin_passwd }} -q "addprinc -pw {{ krb5_admin_user_passwd }} admin"
  tags:
    - adminuser
  
- name: Generate Admin Keytab
  expect:
    command: ktutil 
    responses:
      ktutil: 
        - "add_entry -password -p admin@CLOUDERA.COM -k 1 -e aes256-cts"
        - "wkt /opt/keytabs/admin.keytab"
        - "quit"
      Password: '{{ krb5_admin_user_passwd }}'
  tags:
    - adminuser

- name: copy superuser keytab
  fetch:
    src: /opt/keytabs/hdfs.keytab
    dest: tmp/keytabs/hdfs.keytab
    flat: yes
  tags:
    - copy_keytabs
  
- name: copy admin user keytab
  fetch:
    src: /opt/keytabs/admin.keytab
    dest: tmp/keytabs/admin.keytab
    flat: yes
  tags:
    - copy_keytabs
