---

- name: get pip - NEED REDO
  shell: curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
  tags: done

- name: install pip - NEED REDO
  shell: python get-pip.py
  tags: done

- name: install python lib - NEED REDO
  pip:
    name: pexpect
  tags: done

- name: Create HDFS Superuser - works
  shell: sudo -u cloudera-scm kadmin -w adminword1 -q "addprinc -pw hdfs1234 hdfs"
  tags:
    - done

- name: Generate Keytabs - works
  expect:
    command: ktutil 
    responses:
      ktutil: 
        - "add_entry -password -p hive@CLOUDERA.COM -k 1 -e aes256-cts"
        - "wkt /home/centos/hive.keytab"
        - "quit"
      Password: "hive1234"
  tags:
    - not_done
