---

- name: add yum epel
  yum:
    name: epel-release
    state: present
  become: true
  tags: pip

- name: install pip 
  yum:
    name: python-pip
    state: present
  become: true
  tags: pip

- name: install python lib
  pip:
    name: pexpect
  become: true
  tags: pip

- name: Create HDFS Superuser
  shell: sudo -u cloudera-scm kadmin -w {{ krb5_kdc_admin_passwd }} -q "addprinc -pw {{ k5b5_hdfs_master_passwd }} hdfs"
  tags:
    - not_done

- name: Generate Keytabs - works
  expect:
    command: ktutil 
    responses:
      ktutil: 
        - "add_entry -password -p hive@CLOUDERA.COM -k 1 -e aes256-cts"
        - "wkt /home/centos/hive.keytab"
        - "quit"
      Password: "hive1234"
  tags:
    - not_done
